Fix for issue #101
FIRST-Tech-Challenge/fmltc pull request #104
Opened 2021-09-15 14:28 UTC by hardcopi

This fixes issue #101 and all the places the new dialogs need to be closed properly.

2021-09-15 15:54 UTC, lizlooney commented on server/src/js/uploadVideoFileDialog.js
> +fmltc.UploadVideoFileDialog.STATE_UPLOADING = 3;
In fact, you don't even need to include any changes to this file in this PR, since I added the backdrop code already.

2021-09-15 16:06 UTC, lizlooney requested changes
Please undo all your changes to server/src/js/uploadVideoFileDialog.js

2021-09-22 17:45 UTC, hardcopi commented on server/src/js/uploadVideoFileDialog.js
> +fmltc.UploadVideoFileDialog.STATE_UPLOADING = 3;
I *think* I got it. First time reverting a single file.

2021-09-22 20:44 UTC, lizlooney commented
Looks good. Thanks!

2021-09-22 20:44 UTC, lizlooney approved these changes

2021-09-22 20:45 UTC, lizlooney commented
/gcbrun

2021-09-22 20:53 UTC, merged